### ISSUE TITLE
🛠️ Convert Rquest demo environment to run Rquest Bridge from docker compose

### ISSUE THREAD

**Issue by beforan** [Health-Informatics-UoN/rquest-tools#19]
## Overview

Currently the demo environment for Rquest Bridge runs Rquest Bridge on demand from source.

## Tasks

- [x] Resolve any outstanding code changes in the local source
    - [x] checkout `demo-fixes`
    - [x] tidy up formatting
    - [x] merge `demo-fixes`
- [x] Add Rquest Bridge service entry to `~/docker-compose.yml`
    - ref the latest docker image?
    - [x] Move settings from `appsettings.json` into the docker compose env section for Rquest Bridge
- [x] Test running the app from docker compose
    - Bear in mind on this environment we only stand up specific compose services, not the whole stack
    - e.g. `docker compose up -d rquestbridge rabbitmq minio` or whatever
