### ISSUE TITLE
Trino support in `rquest-omop-worker`

### ISSUE THREAD

**Issue by dcl10** [Health-Informatics-UoN/rquest-tools#24]
## Description
Trino would allow us to query different kinds of databases instead of specifically Postgres. Currently `rquest-omop-worker` is set up to work with Postgres using SQLAlchemy. Also, `rquest-omop-worker` uses an outdated version of SQLAlchemy. It might be worth upgrading.

## Tasks
- [ ] Upgrade `rquest-omop-worker` to use SQLAlchemy 2 (?)
- [ ] Investigate Trino python library.
- [ ] Build trino interaction into `rquest-omop-worker`
- [ ] Redeploy worker to docker hub.
