### ISSUE TITLE
RACKit Project setup

### ISSUE THREAD

**Issue by beforan** [Health-Informatics-UoN/rquest-tools#36]
# Summary

RACKit (Rquest API Client Kit) is a new .NET library for interacting with RQuest.

Update the repository with successfully building projects ready to add features to.

# Tasks

- [x] Add class library project
- [x] Add Test project
- [x] Add GitHub workflow
- [x] Update READMEs

# Acceptance Criteria

- [x] Class Library `lib/Hutch.Rackit` exists and builds
    - [x] `dotnet build` completes successfully
- [x] Test project `tests/Hutch.Rackit.Tests` exists, builds and "tests" pass (no tests yet).
    - [x] `dotnet test` completes successfully
- [x] GitHub workflow for building on PRs to `main`
    - [x] Workflow builds `Hutch.Rackit`
    - [x] Workflow runs tests in `Hutch.Rackit.Tests`
    - [x] Workflow completes successfully on PR
- [x] Documentation added
