### ISSUE TITLE
RACKit Github package registry deployment

### ISSUE THREAD

**Issue by beforan** [Health-Informatics-UoN/rquest-tools#40]
# Summary

# Tasks

- [x] Add Versioning to csproj
- [x] Add workflow for publishing to Github packages
- [x] Test workflow

# Acceptance Criteria

- [x] Workflow exists
- [x] Workflow passes testing succesfully
