### ISSUE TITLE
Fetching Availability Queries for a collection

### ISSUE THREAD

**Issue by beforan** [Health-Informatics-UoN/rquest-tools#43]
# Summary

The RACKit Task API Client needs to be able to check for and fetch availability queries in the queue for a given Collection from a target RQuest instance

# Tasks

- [x] Port FetchQuery from RQuest Bridge's TaskApiClient Service
- [x] Changes to fit library environment vs app
- [x] Unit tests
- [x] Sample app usage
- [x] Documentation
    - (usually needed for new features, and often for other types of work too)

# Acceptance Criteria

- [x] A sample application can, using the library functionality, successfully do the following:
    - [x] Show that there are no availability query jobs waiting in the Rquest Collection's queue, when this is true
    - [x] Show the next query found in the queue if there is one
- [x] Tests pass
- [x] Documentation added
