### ISSUE TITLE
Submitting results for a collection's Availability query job

### ISSUE THREAD

**Issue by beforan** [Health-Informatics-UoN/rquest-tools#45]
## Acceptance Criteria

- [x] RACKit API client can succesfully send results to the target (Rquest) API
- [x] This should work for Availability queries
- [x] Error logging for when a request fails. 
- [x] Unit tests pass
- [x] Sample application shows sending results
- [x] Documentation in .md

## Tasks

- [x] Add the send results method
- [x] Write tests
- [x] Write error handling in method
- [x] Update sample application
- [x] Integration test via sample application
- [x] Update documentation
