### ISSUE TITLE
OMOP CDM Database

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/rquest-tools#66]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

We need a working version of the OMOP CDM that we can use.

For ease - let's use a Azure VM.

pgdump from the existing VM
pgrestore to a Azure Postgres Flexible server

### Acceptance Criteria

- [x] A OMOP CDM database that can be used for development
- [x] A artefact of the dump

### Tasks

- [x] `pgdump` of the OMOP CDM on the existing VM
- [x] `scp` to your local machine (for the file)
- [x] New postgres user / environment: [see discussion](https://github.com/orgs/uon-drs/discussions/23)
- [x] New `hutch-omop` on `drs-nonprod-pgserver`
- [x] `pgrestore` (CLI, Azure portal?, Datagrip) of the file to restore 
- [x] Upload the file to the `Fed A dev` teams chat
- [x] Share credentials for remote access with the team in Github discussion https://github.com/orgs/uon-drs/discussions/39

### Confirm creation

- [x] This issue is ready
