### ISSUE TITLE
Hutch Relay - Project Setup

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/rquest-tools#68]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

Set up a .Net project for Hutch Relay

Hutch.Relay and  inside `rquest-tools/app`
Hutch.Relay.tests `/test`

### Acceptance Criteria

- [x] A new app now exists
- [x] A new test app also
- [ ] Build workflows for the app
- [ ] Published image to Github

### Tasks

- [x] A new .Net 8 project for Hutch Relay
- [x] A new tests project
- [x] Github workflows for build and test
- [x] Dockerfile for application
- [x] Workflow for publishing the docker image to Github registry
    - [x] Tag with timestamp and Git hash
    - [x] Build `x86` and `ARM` images

### Confirm creation

- [x] This issue is ready
