### ISSUE TITLE
Resolve Polling

### ISSUE THREAD

**Issue by AndyRae** [Health-Informatics-UoN/rquest-tools#72]
### Is this the right issue type?

- [x] Yes, I'm planning work for this project team.

### Summary

We need Resolve to poll Relay, get a message, and run the query.

Use this library for now?
https://github.com/justiniso/polling

### Acceptance Criteria

- [ ] Successful message retrieval
- [ ] Successful query result logging

### Tasks

- [ ] Add the polling dependency
- [ ] Add `settings` module, that fetches environment variables to retrieve config
    - [ ] Add `relay_base_url` setting
    - [ ] Add `polling_interval` setting, with 5 second default
- [ ] Implement `polling.poll` to the entrypoint for Resolve daemon
    - [ ] GET request to `/jobs/next`, including `jobId` and `payload` from Relay 
- [ ] 

### Confirm creation

- [x] This issue is ready
